global using Microsoft.EntityFrameworkCore;
global using bawabetak_backend.Data;
global using bawabetak_backend.Extensions.Configurations;
global using bawabetak_backend.Extensions.Pipeline;
global using System.Linq.Expressions;
global using bawabetak_backend.Repositories.Interface;
global using bawabetak_backend.Repositories.Implementation;
global using bawabetak_backend.Dtos;
global using System.Net.Mail;
global using bawabetak_backend.Helpers.Interface;
global using Microsoft.Extensions.Options;
global using Wasla_Backend.Helpers.EmailSender;
global using System.Text.Json;
global using Microsoft.Extensions.Caching.Distributed;
global using Hangfire;
global using Hangfire.Redis.StackExchange;
global using bawabetak_backend.Enums;
global using bawabetak_backend.Helpers.Static;
global using System.Text.Json.Serialization;
global using bawabetak_backend.Exceptions;
global using bawabetak_backend.Middlewares;
global using AutoMapper;
global using System.Reflection;
global using bawabetak_backend.Services.Interface;
global using bawabetak_backend.Helpers.ProgramHelper.DependencyInjection;
global using bawabetak_backend.Extensions.DependencyInjection;
global using Bawabetak.Extensions.Configurations;
global using Microsoft.AspNetCore.Identity;
global using bawabetak_backend.Models;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using bawabetak_backend.Dtos.RoleDtos;
global using bawabetak_backend.Repositories.Abstract;
global using System.Text;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using System.Security.Cryptography;
global using System.Security.Claims;
global using System.IdentityModel.Tokens.Jwt;
global using bawabetak_backend.Strategies.SendVerification.Interface;
global using bawabetak_backend.Exceptions;
global using bawabetak_backend.Strategies.SendVerification.Implementation;
global using bawabetak_backend.Strategies.CheckVerification.Interface;
global using bawabetak_backend.Dtos.AuthDtos;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using bawabetak_backend.Strategies.Login.Interface;
global using bawabetak_backend.Strategies.Login.Implementation;
global using bawabetak_backend.Strategies.CheckVerification.Implementation;
global using System.Security.Cryptography;
global using bawabetak_backend.Strategies.Refresh.Interface;
global using bawabetak_backend.Services.Implementation;
global using bawabetak_backend.Strategies.Refresh.Implementation;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.OpenApi.Any;
global using Microsoft.OpenApi.Models;





